# Generated by Django 6.0.2 on 2026-03-28 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=50, unique=True)),
                ('Account_Number', models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinValueValidator(6)])),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Account_type', models.CharField(choices=[('S', 'Savings'), ('C', 'Current')], default='S', max_length=1)),
            ],
        ),
    ]
